permalink: /posts/:title/

paginate:          5
paginate_path:     "/page/:num/"
excerpt_separator: "<!--more-->"
url:               "http://eddmann.com"

sass:
  sass_dir: _sass
  style:    :compressed

gems:
  - jekyll-paginate
